### ISSUE TITLE
Some files cannot be deleted

### ISSUE THREAD

**Issue by ericroberts** [ericroberts/tint#57]
In my test folder I have a file `animation.gif` but I get this error when trying to delete it:

```
Git::GitExecuteError - git '--git-dir=/Users/Eric/code/projects/tint-demo/.git' '--work-tree=/Users/Eric/code/projects/tint-demo' rm '-f' '--' '/Users/Eric/code/projects/tint-demo/animation.gif'  2>&1:fatal: pathspec '/Users/Eric/code/projects/tint-demo/animation.gif' did not match any files:
```

I have of course confirmed that there is a file at that path. If I try to delete other files in the same folder, that are of type text (.yml, .md, .html) that works fine.

**Comment by ericroberts** [comment]
I think this is because the file existed on the file system but was not committed to git. We'll need to figure out what we should do there.

**Comment by singpolyma** [comment]
Yeah, I don't think this is a real problem because in any production setting there won't be files there that we didn't create.

**Comment by ericroberts** [comment]
Agreed, will close this issue.
